name: Continuous Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Use Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
  test:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: spam_classifier
        path: ${{ github.workspace }}/artifact-staging/
        github_token: ${{ github.token }}
        repository: ${{ github.repository }}
        run_id: 14056045124

    - name: Verify Downloaded Artifact
      run: |
        echo "Files in downloaded artifacts:"
        ls artifacts
