name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Use Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Prepare Artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact-staging/
          echo "Sample artifact content" > ${{ github.workspace }}/artifact-staging/sample.txt

      - name: Upload Pipeline Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spam_classifier
          path: ${{ github.workspace }}/artifact-staging/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: spam_classifier  # Ensure the names match
        path: artifacts

    - name: Verify Downloaded Artifact
      run: |
        echo "Files in downloaded artifacts:"
        ls artifacts
